#!/bin/sh
# Copyright 2004 Ulrich Hecht <uli@suse.de>

# This file is part of ddiwrapper.

# ddiwrapper is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

# creates a WINE setup suitable for ddiwrapper in your home directory; called
# by the ddiwrapper wrapper script.

test -e $HOME/.ddiwrapper && exit 0
mkdir -p $HOME/.ddiwrapper
cd $HOME/.ddiwrapper
cp -p /usr/share/ddiwrapper/wine.config config
mkdir -p c/windows/system
